server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
  mail:
    host: smtp.gmail.com
    password: <Login password to SMTP server>
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: <Login User to SMTP server>
reg-app:
  message:
    regMailSubject: User Registration Success
    regMailBodyTemplateFile: UNLOCK-ACC-EMAIL-BODY-TEMPLATE.txt	    
    
